# name of object file
obj-m := ??? 

# cross compilation env vars
ARCH := ???
CROSS_COMPILE := ???

# Set KDIR to kernel source dir
KDIR := ???
PWD := $(shell pwd)

all:
	make  ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) -C ???  M=??? modules

